apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Max2535/team-stack.git
    targetRevision: main
    path: infra/k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: team
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
