apiVersion: v1
kind: ConfigMap
metadata:
  name: team-api-config
data:
  APP_NAME: team-api
  APP_ENV: prod
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  LOG_LEVEL: info
  REDIS_ADDR: redis:6379
  KAFKA_BROKER: kafka:9092
  KAFKA_TOPIC: team-events
  JWT_ACCESS_TTL: 15m
  DB_MAX_OPEN: "20"
  DB_MAX_IDLE: "5"
  DB_CONN_MAX_LIFE: 30m
